/**
 * Spotify Web API with fixes and improvements from sonalluxLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { CategoriesController } from '../src';
import { testClient } from './testClient';
import { expectHeadersToMatch, makeApiCall } from './testHelper';

describe('CategoriesController', () => {
  let controller : CategoriesController;

  beforeAll(() => {
    controller = new CategoriesController(testClient);
  });

  it('should Test get-categories', async () => {
    const locale = 'sv_SE';

    const limit = 20;

    const offset = 0;

    const response = await makeApiCall(
      () => controller.getCategories(locale, limit, offset)
    );

    expect(response.statusCode).toBe(200);

    const expectedHeaders = { 'Content-Type': ['application/json', true] };

    expectHeadersToMatch(response.headers, expectedHeaders);
  });

  it('should Test get-a-category', async () => {
    const categoryId = 'dinner';

    const locale = 'sv_SE';

    const response = await makeApiCall(
      () => controller.getACategory(categoryId, locale)
    );

    expect(response.statusCode).toBe(200);

    const expectedHeaders = { 'Content-Type': ['application/json', true] };

    expectHeadersToMatch(response.headers, expectedHeaders);
  });
});
