/**
 * Spotify Web API with fixes and improvements from sonalluxLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ChaptersController } from '../src';
import { testClient } from './testClient';
import { expectHeadersToMatch, makeApiCall } from './testHelper';

describe('ChaptersController', () => {
  let controller : ChaptersController;

  beforeAll(() => {
    controller = new ChaptersController(testClient);
  });

  it('should Test get-a-chapter', async () => {
    const id = '0D5wENdkdwbqlrHoaJ9g29';

    const market = 'ES';

    const response = await makeApiCall(
      () => controller.getAChapter(id, market)
    );

    expect(response.statusCode).toBe(200);

    const expectedHeaders = { 'Content-Type': ['application/json', true] };

    expectHeadersToMatch(response.headers, expectedHeaders);
  });

  it('should Test get-several-chapters', async () => {
    const ids = '0IsXVP0JmcB2adSE338GkK,3ZXb8FKZGU0EHALYX6uCzU,0D5wENdkdwbqlrHoaJ9g29';

    const market = 'ES';

    const response = await makeApiCall(
      () => controller.getSeveralChapters(ids, market)
    );

    expect(response.statusCode).toBe(200);

    const expectedHeaders = { 'Content-Type': ['application/json', true] };

    expectHeadersToMatch(response.headers, expectedHeaders);
  });
});
