/**
 * Spotify Web API with fixes and improvements from sonalluxLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { MarketsController } from '../src';
import { testClient } from './testClient';
import { expectHeadersToMatch, makeApiCall } from './testHelper';

describe('MarketsController', () => {
  let controller : MarketsController;

  beforeAll(() => {
    controller = new MarketsController(testClient);
  });

  it('should Test get-available-markets', async () => {
    const response = await makeApiCall(
      () => controller.getAvailableMarkets()
    );

    expect(response.statusCode).toBe(200);

    const expectedHeaders = { 'Content-Type': ['application/json', true] };

    expectHeadersToMatch(response.headers, expectedHeaders);
  });
});
