/**
 * Spotify Web API with fixes and improvements from sonalluxLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Client, Configuration, Environment } from '../src';

export const testClient = new Client(createConfigurationFromEnvironment());

function createConfigurationFromEnvironment(): Partial<Configuration> {
  const config: Partial<Configuration> = {};

  const environment = process.env.SPOTIFY_WEB_API_WITH_FIXES_AND_IMPROVEMENTS_FROM_SONALLUX_LIB_ENVIRONMENT;
  const timeout = process.env.SPOTIFY_WEB_API_WITH_FIXES_AND_IMPROVEMENTS_FROM_SONALLUX_LIB_TIMEOUT;
  const oAuthClientId = process.env.SPOTIFY_WEB_API_WITH_FIXES_AND_IMPROVEMENTS_FROM_SONALLUX_LIB_O_AUTH_CLIENT_ID;
  const oAuthClientSecret = process.env.SPOTIFY_WEB_API_WITH_FIXES_AND_IMPROVEMENTS_FROM_SONALLUX_LIB_O_AUTH_CLIENT_SECRET;
  const oAuthRedirectUri = process.env.SPOTIFY_WEB_API_WITH_FIXES_AND_IMPROVEMENTS_FROM_SONALLUX_LIB_O_AUTH_REDIRECT_URI;

  if (environment !== undefined) {
    config.environment = environment as Environment;
  }

  if (timeout !== undefined && timeout !== '') {
    config.timeout = parseInt(timeout);
  }

  if (
    oAuthClientId !== undefined
    && oAuthClientSecret !== undefined
    && oAuthRedirectUri !== undefined
  ) {
    config.authorizationCodeAuthCredentials = {
      oAuthClientId: oAuthClientId,
      oAuthClientSecret: oAuthClientSecret,
      oAuthRedirectUri: oAuthRedirectUri,
    };
  }

  return config;
}
