/**
 * Spotify Web API with fixes and improvements from sonalluxLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { oneOf, Schema, validateAndMap } from '../../schema';
import { EpisodeObject, episodeObjectSchema } from '../episodeObject';
import { TrackObject, trackObjectSchema } from '../trackObject';

/** This is a container type for one-of types. */
export type CurrentlyPlayingObjectItem = TrackObject | EpisodeObject;

export const currentlyPlayingObjectItemSchema: Schema<CurrentlyPlayingObjectItem> = oneOf(
  [trackObjectSchema, episodeObjectSchema]
);

export namespace CurrentlyPlayingObjectItem {
  /**
   * Validation method to narrow down union type to TrackObject type case.
   *
   * This is TrackObject case.
   */
  export function isTrackObject(value: unknown): value is TrackObject {
    const validationResult = validateAndMap(value, trackObjectSchema);
    return validationResult.errors === false;
  }

  /**
   * Validation method to narrow down union type to EpisodeObject type case.
   *
   * This is EpisodeObject case.
   */
  export function isEpisodeObject(value: unknown): value is EpisodeObject {
    const validationResult = validateAndMap(value, episodeObjectSchema);
    return validationResult.errors === false;
  }
}
