/**
 * Spotify Web API with fixes and improvements from sonalluxLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core';
import { CategoryObject, categoryObjectSchema } from '../models/categoryObject';
import {
  PagedCategories,
  pagedCategoriesSchema,
} from '../models/pagedCategories';
import { number, optional, string } from '../schema';
import { BaseController } from './baseController';
import { ForbiddenError } from '../errors/forbiddenError';
import { TooManyRequestsError } from '../errors/tooManyRequestsError';
import { UnauthorizedError } from '../errors/unauthorizedError';

export class CategoriesController extends BaseController {
  /**
   * Get a list of categories used to tag items in Spotify (on, for example, the Spotify player’s
   * “Browse” tab).
   *
   *
   * @param locale
   * @param limit  Example: 20
   * @param offset Example: 0
   * @return Response from the API call


   */
  async getCategories(
    locale?: string,
    limit?: number,
    offset?: number,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<PagedCategories>> {
    const req = this.createRequest('GET', '/browse/categories');
    const mapped = req.prepareArgs({
      locale: [locale, optional(string())],
      limit: [limit, optional(number())],
      offset: [offset, optional(number())],
    });
    req.query('locale', mapped.locale);
    req.query('limit', mapped.limit);
    req.query('offset', mapped.offset);
    req.throwOn(
      401,
      UnauthorizedError,
      'Bad or expired token. This can happen if the user revoked a token or\nthe access token has expired. You should re-authenticate the user.\n'
    );
    req.throwOn(
      403,
      ForbiddenError,
      "Bad OAuth request (wrong consumer key, bad nonce, expired\ntimestamp...). Unfortunately, re-authenticating the user won't help here.\n"
    );
    req.throwOn(
      429,
      TooManyRequestsError,
      'The app has exceeded its rate limits.\n'
    );
    req.authenticate([{ oauth20: true }]);
    return req.callAsJson(pagedCategoriesSchema, requestOptions);
  }

  /**
   * Get a single category used to tag items in Spotify (on, for example, the Spotify player’s “Browse”
   * tab).
   *
   *
   * @param categoryId
   * @param locale
   * @return Response from the API call


   */
  async getACategory(
    categoryId: string,
    locale?: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<CategoryObject>> {
    const req = this.createRequest('GET');
    const mapped = req.prepareArgs({
      categoryId: [categoryId, string()],
      locale: [locale, optional(string())],
    });
    req.query('locale', mapped.locale);
    req.appendTemplatePath`/browse/categories/${mapped.categoryId}`;
    req.throwOn(
      401,
      UnauthorizedError,
      'Bad or expired token. This can happen if the user revoked a token or\nthe access token has expired. You should re-authenticate the user.\n'
    );
    req.throwOn(
      403,
      ForbiddenError,
      "Bad OAuth request (wrong consumer key, bad nonce, expired\ntimestamp...). Unfortunately, re-authenticating the user won't help here.\n"
    );
    req.throwOn(
      429,
      TooManyRequestsError,
      'The app has exceeded its rate limits.\n'
    );
    req.authenticate([{ oauth20: true }]);
    return req.callAsJson(categoryObjectSchema, requestOptions);
  }
}
