/**
 * Spotify Web API with fixes and improvements from sonalluxLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core';
import { ManyGenres, manyGenresSchema } from '../models/manyGenres';
import { BaseController } from './baseController';
import { ForbiddenError } from '../errors/forbiddenError';
import { TooManyRequestsError } from '../errors/tooManyRequestsError';
import { UnauthorizedError } from '../errors/unauthorizedError';

export class GenresController extends BaseController {
  /**
   * Retrieve a list of available genres seed parameter values for [recommendations](/documentation/web-
   * api/reference/get-recommendations).
   *
   *
   * @return Response from the API call


   */
  async getRecommendationGenres(
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<ManyGenres>> {
    const req = this.createRequest(
      'GET',
      '/recommendations/available-genre-seeds'
    );
    req.throwOn(
      401,
      UnauthorizedError,
      'Bad or expired token. This can happen if the user revoked a token or\nthe access token has expired. You should re-authenticate the user.\n'
    );
    req.throwOn(
      403,
      ForbiddenError,
      "Bad OAuth request (wrong consumer key, bad nonce, expired\ntimestamp...). Unfortunately, re-authenticating the user won't help here.\n"
    );
    req.throwOn(
      429,
      TooManyRequestsError,
      'The app has exceeded its rate limits.\n'
    );
    req.authenticate([{ oauth20: true }]);
    return req.callAsJson(manyGenresSchema, requestOptions);
  }
}
