/**
 * Spotify Web API with fixes and improvements from sonalluxLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema } from '../schema';
import { ReasonEnum, reasonEnumSchema } from './reasonEnum';

export interface AlbumRestrictionObject {
  /**
   * The reason for the restriction. Albums may be restricted if the content is not available in a given market, to the user's subscription type, or when the user's account is set to not play explicit content.
   * Additional reasons may be added in the future.
   */
  reason?: ReasonEnum;
}

export const albumRestrictionObjectSchema: Schema<AlbumRestrictionObject> = object(
  { reason: ['reason', optional(reasonEnumSchema)] }
);
