/**
 * Spotify Web API with fixes and improvements from sonalluxLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for AlbumGroupEnum
 */
export enum AlbumGroupEnum {
  Album = 'album',
  Single = 'single',
  Compilation = 'compilation',
  AppearsOn = 'appears_on',
}

/**
 * Schema for AlbumGroupEnum
 */
export const albumGroupEnumSchema: Schema<AlbumGroupEnum> = stringEnum(
  AlbumGroupEnum
);
