/**
 * Spotify Web API with fixes and improvements from sonalluxLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for AlbumTypeEnum
 */
export enum AlbumTypeEnum {
  Album = 'album',
  Single = 'single',
  Compilation = 'compilation',
}

/**
 * Schema for AlbumTypeEnum
 */
export const albumTypeEnumSchema: Schema<AlbumTypeEnum> = stringEnum(
  AlbumTypeEnum
);
