/**
 * Spotify Web API with fixes and improvements from sonalluxLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface AuthorObject {
  /** The name of the author. */
  name?: string;
}

export const authorObjectSchema: Schema<AuthorObject> = object({
  name: ['name', optional(string())],
});
