/**
 * Spotify Web API with fixes and improvements from sonalluxLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, Schema, string } from '../schema';
import { ImageObject, imageObjectSchema } from './imageObject';

export interface CategoryObject {
  /** A link to the Web API endpoint returning full details of the category. */
  href: string;
  /** The category icon, in various sizes. */
  icons: ImageObject[];
  /** The [Spotify category ID](/documentation/web-api/concepts/spotify-uris-ids) of the category. */
  id: string;
  /** The name of the category. */
  name: string;
}

export const categoryObjectSchema: Schema<CategoryObject> = object({
  href: ['href', string()],
  icons: ['icons', array(lazy(() => imageObjectSchema))],
  id: ['id', string()],
  name: ['name', string()],
});
