/**
 * Spotify Web API with fixes and improvements from sonalluxLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  lazy,
  nullable,
  number,
  object,
  optional,
  Schema,
  string,
} from '../schema';
import {
  ChapterRestrictionObject,
  chapterRestrictionObjectSchema,
} from './chapterRestrictionObject';
import {
  ExternalUrlObject,
  externalUrlObjectSchema,
} from './externalUrlObject';
import { ImageObject, imageObjectSchema } from './imageObject';
import {
  ReleaseDatePrecisionEnum,
  releaseDatePrecisionEnumSchema,
} from './releaseDatePrecisionEnum';
import {
  ResumePointObject,
  resumePointObjectSchema,
} from './resumePointObject';

export interface ChapterBase {
  /** A URL to a 30 second preview (MP3 format) of the chapter. `null` if not available. */
  audioPreviewUrl: string | null;
  /** A list of the countries in which the chapter can be played, identified by their [ISO 3166-1 alpha-2](http://en.wikipedia.org/wiki/ISO_3166-1_alpha-2) code. */
  availableMarkets?: string[];
  /** The number of the chapter */
  chapterNumber: number;
  /** A description of the chapter. HTML tags are stripped away from this field, use `html_description` field in case HTML tags are needed. */
  description: string;
  /** A description of the chapter. This field may contain HTML tags. */
  htmlDescription: string;
  /** The chapter length in milliseconds. */
  durationMs: number;
  /** Whether or not the chapter has explicit content (true = yes it does; false = no it does not OR unknown). */
  explicit: boolean;
  /** External URLs for this chapter. */
  externalUrls: ExternalUrlObject;
  /** A link to the Web API endpoint providing full details of the chapter. */
  href: string;
  /** The [Spotify ID](/documentation/web-api/concepts/spotify-uris-ids) for the chapter. */
  id: string;
  /** The cover art for the chapter in various sizes, widest first. */
  images: ImageObject[];
  /** True if the chapter is playable in the given market. Otherwise false. */
  isPlayable: boolean;
  /** A list of the languages used in the chapter, identified by their [ISO 639-1](https://en.wikipedia.org/wiki/ISO_639) code. */
  languages: string[];
  /** The name of the chapter. */
  name: string;
  /** The date the chapter was first released, for example `"1981-12-15"`. Depending on the precision, it might be shown as `"1981"` or `"1981-12"`. */
  releaseDate: string;
  /** The precision with which `release_date` value is known. */
  releaseDatePrecision: ReleaseDatePrecisionEnum;
  /** The user's most recent position in the chapter. Set if the supplied access token is a user token and has the scope 'user-read-playback-position'. */
  resumePoint?: ResumePointObject;
  /** The object type. */
  type: string;
  /** The [Spotify URI](/documentation/web-api/concepts/spotify-uris-ids) for the chapter. */
  uri: string;
  /** Included in the response when a content restriction is applied. */
  restrictions?: ChapterRestrictionObject;
}

export const chapterBaseSchema: Schema<ChapterBase> = object({
  audioPreviewUrl: ['audio_preview_url', nullable(string())],
  availableMarkets: ['available_markets', optional(array(string()))],
  chapterNumber: ['chapter_number', number()],
  description: ['description', string()],
  htmlDescription: ['html_description', string()],
  durationMs: ['duration_ms', number()],
  explicit: ['explicit', boolean()],
  externalUrls: ['external_urls', lazy(() => externalUrlObjectSchema)],
  href: ['href', string()],
  id: ['id', string()],
  images: ['images', array(lazy(() => imageObjectSchema))],
  isPlayable: ['is_playable', boolean()],
  languages: ['languages', array(string())],
  name: ['name', string()],
  releaseDate: ['release_date', string()],
  releaseDatePrecision: [
    'release_date_precision',
    releaseDatePrecisionEnumSchema,
  ],
  resumePoint: ['resume_point', optional(lazy(() => resumePointObjectSchema))],
  type: ['type', string()],
  uri: ['uri', string()],
  restrictions: [
    'restrictions',
    optional(lazy(() => chapterRestrictionObjectSchema)),
  ],
});
