/**
 * Spotify Web API with fixes and improvements from sonalluxLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema, string } from '../schema';
import {
  ExternalUrlObject,
  externalUrlObjectSchema,
} from './externalUrlObject';

export interface ContextObject {
  /** The object type, e.g. "artist", "playlist", "album", "show". */
  type?: string;
  /** A link to the Web API endpoint providing full details of the track. */
  href?: string;
  /** External URLs for this context. */
  externalUrls?: ExternalUrlObject;
  /** The [Spotify URI](/documentation/web-api/concepts/spotify-uris-ids) for the context. */
  uri?: string;
}

export const contextObjectSchema: Schema<ContextObject> = object({
  type: ['type', optional(string())],
  href: ['href', optional(string())],
  externalUrls: [
    'external_urls',
    optional(lazy(() => externalUrlObjectSchema)),
  ],
  uri: ['uri', optional(string())],
});
