/**
 * Spotify Web API with fixes and improvements from sonalluxLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface CopyrightObject {
  /** The copyright text for this content. */
  text?: string;
  /** The type of copyright: `C` = the copyright, `P` = the sound recording (performance) copyright. */
  type?: string;
}

export const copyrightObjectSchema: Schema<CopyrightObject> = object({
  text: ['text', optional(string())],
  type: ['type', optional(string())],
});
