/**
 * Spotify Web API with fixes and improvements from sonalluxLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  bigint,
  boolean,
  lazy,
  number,
  object,
  optional,
  Schema,
  string,
} from '../schema';
import {
  CurrentlyPlayingContextObjectItem,
  currentlyPlayingContextObjectItemSchema,
} from './containers/currentlyPlayingContextObjectItem';
import { ContextObject, contextObjectSchema } from './contextObject';
import { DeviceObject, deviceObjectSchema } from './deviceObject';
import { DisallowsObject, disallowsObjectSchema } from './disallowsObject';

export interface CurrentlyPlayingContextObject {
  /** The device that is currently active. */
  device?: DeviceObject;
  /** off, track, context */
  repeatState?: string;
  /** If shuffle is on or off. */
  shuffleState?: boolean;
  /** A Context Object. Can be `null`. */
  context?: ContextObject;
  /** Unix Millisecond Timestamp when data was fetched. */
  timestamp?: bigint;
  /** Progress into the currently playing track or episode. Can be `null`. */
  progressMs?: number;
  /** If something is currently playing, return `true`. */
  isPlaying?: boolean;
  /** The currently playing track or episode. Can be `null`. */
  item?: CurrentlyPlayingContextObjectItem;
  /** The object type of the currently playing item. Can be one of `track`, `episode`, `ad` or `unknown`. */
  currentlyPlayingType?: string;
  /** Allows to update the user interface based on which playback actions are available within the current context. */
  actions?: DisallowsObject;
}

export const currentlyPlayingContextObjectSchema: Schema<CurrentlyPlayingContextObject> = object(
  {
    device: ['device', optional(lazy(() => deviceObjectSchema))],
    repeatState: ['repeat_state', optional(string())],
    shuffleState: ['shuffle_state', optional(boolean())],
    context: ['context', optional(lazy(() => contextObjectSchema))],
    timestamp: ['timestamp', optional(bigint())],
    progressMs: ['progress_ms', optional(number())],
    isPlaying: ['is_playing', optional(boolean())],
    item: ['item', optional(currentlyPlayingContextObjectItemSchema)],
    currentlyPlayingType: ['currently_playing_type', optional(string())],
    actions: ['actions', optional(lazy(() => disallowsObjectSchema))],
  }
);
