/**
 * Spotify Web API with fixes and improvements from sonalluxLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema } from '../schema';
import {
  CursorPagingSimplifiedArtistObject,
  cursorPagingSimplifiedArtistObjectSchema,
} from './cursorPagingSimplifiedArtistObject';

export interface CursorPagedArtists {
  artists: CursorPagingSimplifiedArtistObject;
}

export const cursorPagedArtistsSchema: Schema<CursorPagedArtists> = object({
  artists: ['artists', lazy(() => cursorPagingSimplifiedArtistObjectSchema)],
});
