/**
 * Spotify Web API with fixes and improvements from sonalluxLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, object, optional, Schema } from '../schema';

export interface DisallowsObject {
  /** Interrupting playback. Optional field. */
  interruptingPlayback?: boolean;
  /** Pausing. Optional field. */
  pausing?: boolean;
  /** Resuming. Optional field. */
  resuming?: boolean;
  /** Seeking playback location. Optional field. */
  seeking?: boolean;
  /** Skipping to the next context. Optional field. */
  skippingNext?: boolean;
  /** Skipping to the previous context. Optional field. */
  skippingPrev?: boolean;
  /** Toggling repeat context flag. Optional field. */
  togglingRepeatContext?: boolean;
  /** Toggling shuffle flag. Optional field. */
  togglingShuffle?: boolean;
  /** Toggling repeat track flag. Optional field. */
  togglingRepeatTrack?: boolean;
  /** Transfering playback between devices. Optional field. */
  transferringPlayback?: boolean;
}

export const disallowsObjectSchema: Schema<DisallowsObject> = object({
  interruptingPlayback: ['interrupting_playback', optional(boolean())],
  pausing: ['pausing', optional(boolean())],
  resuming: ['resuming', optional(boolean())],
  seeking: ['seeking', optional(boolean())],
  skippingNext: ['skipping_next', optional(boolean())],
  skippingPrev: ['skipping_prev', optional(boolean())],
  togglingRepeatContext: ['toggling_repeat_context', optional(boolean())],
  togglingShuffle: ['toggling_shuffle', optional(boolean())],
  togglingRepeatTrack: ['toggling_repeat_track', optional(boolean())],
  transferringPlayback: ['transferring_playback', optional(boolean())],
});
