/**
 * Spotify Web API with fixes and improvements from sonalluxLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface EpisodeRestrictionObject {
  /**
   * The reason for the restriction. Supported values:
   * - `market` - The content item is not available in the given market.
   * - `product` - The content item is not available for the user's subscription type.
   * - `explicit` - The content item is explicit and the user's account is set to not play explicit content.
   * Additional reasons may be added in the future.
   * **Note**: If you use this field, make sure that your application safely handles unknown values.
   */
  reason?: string;
}

export const episodeRestrictionObjectSchema: Schema<EpisodeRestrictionObject> = object(
  { reason: ['reason', optional(string())] }
);
