/**
 * Spotify Web API with fixes and improvements from sonalluxLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, Schema, string } from '../schema';

export interface ErrorObject {
  /** The HTTP status code (also returned in the response header; see [Response Status Codes](/documentation/web-api/concepts/api-calls#response-status-codes) for more information). */
  status: number;
  /** A short description of the cause of the error. */
  message: string;
}

export const errorObjectSchema: Schema<ErrorObject> = object({
  status: ['status', number()],
  message: ['message', string()],
});
