/**
 * Spotify Web API with fixes and improvements from sonalluxLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { nullable, number, object, optional, Schema, string } from '../schema';

export interface FollowersObject {
  /** This will always be set to null, as the Web API does not support it at the moment. */
  href?: string | null;
  /** The total number of followers. */
  total?: number;
}

export const followersObjectSchema: Schema<FollowersObject> = object({
  href: ['href', optional(nullable(string()))],
  total: ['total', optional(number())],
});
