/**
 * Spotify Web API with fixes and improvements from sonalluxLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { nullable, number, object, Schema, string } from '../schema';

export interface ImageObject {
  /** The source URL of the image. */
  url: string;
  /** The image height in pixels. */
  height: number | null;
  /** The image width in pixels. */
  width: number | null;
}

export const imageObjectSchema: Schema<ImageObject> = object({
  url: ['url', string()],
  height: ['height', nullable(number())],
  width: ['width', nullable(number())],
});
