/**
 * Spotify Web API with fixes and improvements from sonalluxLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for ItemType3Enum
 */
export enum ItemType3Enum {
  Artist = 'artist',
  User = 'user',
}

/**
 * Schema for ItemType3Enum
 */
export const itemType3EnumSchema: Schema<ItemType3Enum> = stringEnum(
  ItemType3Enum
);
