/**
 * Spotify Web API with fixes and improvements from sonalluxLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for ItemType1Enum
 */
export enum ItemType1Enum {
  Artist = 'artist',
}

/**
 * Schema for ItemType1Enum
 */
export const itemType1EnumSchema: Schema<ItemType1Enum> = stringEnum(
  ItemType1Enum
);
