/**
 * Spotify Web API with fixes and improvements from sonalluxLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, Schema } from '../schema';
import { TrackObject, trackObjectSchema } from './trackObject';

export interface ManyTracks {
  tracks: TrackObject[];
}

export const manyTracksSchema: Schema<ManyTracks> = object({
  tracks: ['tracks', array(lazy(() => trackObjectSchema))],
});
