/**
 * Spotify Web API with fixes and improvements from sonalluxLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, Schema } from '../schema';
import { AudiobookObject, audiobookObjectSchema } from './audiobookObject';

export interface ManyAudiobooks {
  audiobooks: AudiobookObject[];
}

export const manyAudiobooksSchema: Schema<ManyAudiobooks> = object({
  audiobooks: ['audiobooks', array(lazy(() => audiobookObjectSchema))],
});
