/**
 * Spotify Web API with fixes and improvements from sonalluxLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, Schema } from '../schema';
import { AlbumObject, albumObjectSchema } from './albumObject';

export interface ManyAlbums {
  albums: AlbumObject[];
}

export const manyAlbumsSchema: Schema<ManyAlbums> = object({
  albums: ['albums', array(lazy(() => albumObjectSchema))],
});
