/**
 * Spotify Web API with fixes and improvements from sonalluxLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, Schema } from '../schema';
import { DeviceObject, deviceObjectSchema } from './deviceObject';

export interface ManyDevices {
  devices: DeviceObject[];
}

export const manyDevicesSchema: Schema<ManyDevices> = object({
  devices: ['devices', array(lazy(() => deviceObjectSchema))],
});
