/**
 * Spotify Web API with fixes and improvements from sonalluxLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, Schema } from '../schema';
import { ChapterObject, chapterObjectSchema } from './chapterObject';

export interface ManyChapters {
  chapters: ChapterObject[];
}

export const manyChaptersSchema: Schema<ManyChapters> = object({
  chapters: ['chapters', array(lazy(() => chapterObjectSchema))],
});
