/**
 * Spotify Web API with fixes and improvements from sonalluxLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, object, Schema, string } from '../schema';

export interface ManyGenres {
  genres: string[];
}

export const manyGenresSchema: Schema<ManyGenres> = object({
  genres: ['genres', array(string())],
});
