/**
 * Spotify Web API with fixes and improvements from sonalluxLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, Schema } from '../schema';
import { EpisodeObject, episodeObjectSchema } from './episodeObject';

export interface ManyEpisodes {
  episodes: EpisodeObject[];
}

export const manyEpisodesSchema: Schema<ManyEpisodes> = object({
  episodes: ['episodes', array(lazy(() => episodeObjectSchema))],
});
