/**
 * Spotify Web API with fixes and improvements from sonalluxLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { bigint, number, object, optional, Schema, string } from '../schema';

export interface Meta {
  /** The version of the Analyzer used to analyze this track. */
  analyzerVersion?: string;
  /** The platform used to read the track's audio data. */
  platform?: string;
  /** A detailed status code for this track. If analysis data is missing, this code may explain why. */
  detailedStatus?: string;
  /** The return code of the analyzer process. 0 if successful, 1 if any errors occurred. */
  statusCode?: number;
  /** The Unix timestamp (in seconds) at which this track was analyzed. */
  timestamp?: bigint;
  /** The amount of time taken to analyze this track. */
  analysisTime?: number;
  /** The method used to read the track's audio data. */
  inputProcess?: string;
}

export const metaSchema: Schema<Meta> = object({
  analyzerVersion: ['analyzer_version', optional(string())],
  platform: ['platform', optional(string())],
  detailedStatus: ['detailed_status', optional(string())],
  statusCode: ['status_code', optional(number())],
  timestamp: ['timestamp', optional(bigint())],
  analysisTime: ['analysis_time', optional(number())],
  inputProcess: ['input_process', optional(string())],
});
