/**
 * Spotify Web API with fixes and improvements from sonalluxLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, numberEnum } from '../schema';

/**
 * Enum for ModeEnum
 */
export enum ModeEnum {
  EnumMinus1 = -1,
  Enum0 = 0,
  Enum1 = 1,
}

/**
 * Schema for ModeEnum
 */
export const modeEnumSchema: Schema<ModeEnum> = numberEnum(ModeEnum);
