/**
 * Spotify Web API with fixes and improvements from sonalluxLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface NarratorObject {
  /** The name of the Narrator. */
  name?: string;
}

export const narratorObjectSchema: Schema<NarratorObject> = object({
  name: ['name', optional(string())],
});
