/**
 * Spotify Web API with fixes and improvements from sonalluxLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for OAuthScopeEnum
 */
export enum OAuthScopeEnum {
  AppRemoteControl = 'app-remote-control',
  PlaylistReadPrivate = 'playlist-read-private',
  PlaylistReadCollaborative = 'playlist-read-collaborative',
  PlaylistModifyPublic = 'playlist-modify-public',
  PlaylistModifyPrivate = 'playlist-modify-private',
  UserLibraryRead = 'user-library-read',
  UserLibraryModify = 'user-library-modify',
  UserReadPrivate = 'user-read-private',
  UserReadEmail = 'user-read-email',
  UserFollowRead = 'user-follow-read',
  UserFollowModify = 'user-follow-modify',
  UserTopRead = 'user-top-read',
  UserReadPlaybackPosition = 'user-read-playback-position',
  UserReadPlaybackState = 'user-read-playback-state',
  UserReadRecentlyPlayed = 'user-read-recently-played',
  UserReadCurrentlyPlaying = 'user-read-currently-playing',
  UserModifyPlaybackState = 'user-modify-playback-state',
  UgcImageUpload = 'ugc-image-upload',
  Streaming = 'streaming',
}

/**
 * Schema for OAuthScopeEnum
 */
export const oAuthScopeEnumSchema: Schema<OAuthScopeEnum> = stringEnum(
  OAuthScopeEnum
);
