/**
 * Spotify Web API with fixes and improvements from sonalluxLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema } from '../schema';
import {
  PagingSimplifiedAlbumObject,
  pagingSimplifiedAlbumObjectSchema,
} from './pagingSimplifiedAlbumObject';

export interface PagedAlbums {
  albums: PagingSimplifiedAlbumObject;
}

export const pagedAlbumsSchema: Schema<PagedAlbums> = object({
  albums: ['albums', lazy(() => pagingSimplifiedAlbumObjectSchema)],
});
