/**
 * Spotify Web API with fixes and improvements from sonalluxLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema, string } from '../schema';
import { ContextObject, contextObjectSchema } from './contextObject';
import { TrackObject, trackObjectSchema } from './trackObject';

export interface PlayHistoryObject {
  /** The track the user listened to. */
  track?: TrackObject;
  /** The date and time the track was played. */
  playedAt?: string;
  /** The context the track was played from. */
  context?: ContextObject;
}

export const playHistoryObjectSchema: Schema<PlayHistoryObject> = object({
  track: ['track', optional(lazy(() => trackObjectSchema))],
  playedAt: ['played_at', optional(string())],
  context: ['context', optional(lazy(() => contextObjectSchema))],
});
