/**
 * Spotify Web API with fixes and improvements from sonalluxLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, lazy, object, optional, Schema, string } from '../schema';
import {
  PlaylistTrackObjectTrack,
  playlistTrackObjectTrackSchema,
} from './containers/playlistTrackObjectTrack';
import {
  PlaylistUserObject,
  playlistUserObjectSchema,
} from './playlistUserObject';

export interface PlaylistTrackObject {
  /** The date and time the track or episode was added. _**Note**: some very old playlists may return `null` in this field._ */
  addedAt?: string;
  /** The Spotify user who added the track or episode. _**Note**: some very old playlists may return `null` in this field._ */
  addedBy?: PlaylistUserObject;
  /** Whether this track or episode is a [local file](/documentation/web-api/concepts/playlists/#local-files) or not. */
  isLocal?: boolean;
  /** Information about the track or episode. */
  track?: PlaylistTrackObjectTrack;
}

export const playlistTrackObjectSchema: Schema<PlaylistTrackObject> = object({
  addedAt: ['added_at', optional(string())],
  addedBy: ['added_by', optional(lazy(() => playlistUserObjectSchema))],
  isLocal: ['is_local', optional(boolean())],
  track: ['track', optional(playlistTrackObjectTrackSchema)],
});
