/**
 * Spotify Web API with fixes and improvements from sonalluxLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, object, optional, Schema, string } from '../schema';

export interface PlaylistsRequest {
  /** The new name for the playlist, for example `"My New Playlist Title"` */
  name?: string;
  /** If `true` the playlist will be public, if `false` it will be private. */
  mPublic?: boolean;
  /**
   * If `true`, the playlist will become collaborative and other users will be able to modify the playlist in their Spotify client. <br/>
   * _**Note**: You can only set `collaborative` to `true` on non-public playlists._
   */
  collaborative?: boolean;
  /** Value for playlist description as displayed in Spotify Clients and in the Web API. */
  description?: string;
}

export const playlistsRequestSchema: Schema<PlaylistsRequest> = object({
  name: ['name', optional(string())],
  mPublic: ['public', optional(boolean())],
  collaborative: ['collaborative', optional(boolean())],
  description: ['description', optional(string())],
});
