/**
 * Spotify Web API with fixes and improvements from sonalluxLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, object, optional, Schema } from '../schema';

export interface PlaylistsFollowersRequest {
  /** Defaults to `true`. If `true` the playlist will be included in user's public playlists, if `false` it will remain private. */
  mPublic?: boolean;
}

export const playlistsFollowersRequestSchema: Schema<PlaylistsFollowersRequest> = object(
  { mPublic: ['public', optional(boolean())] }
);
