/**
 * Spotify Web API with fixes and improvements from sonalluxLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema, string } from '../schema';
import { Track1, track1Schema } from './track1';

export interface PlaylistsTracksRequest2 {
  /**
   * An array of objects containing [Spotify URIs](/documentation/web-api/concepts/spotify-uris-ids) of the tracks or episodes to remove.
   * For example: `{ "tracks": [{ "uri": "spotify:track:4iV5W9uYEdYUVa79Axb7Rh" },{ "uri": "spotify:track:1301WleyT98MSxVHPZCA6M" }] }`. A maximum of 100 objects can be sent at once.
   */
  tracks: Track1[];
  /**
   * The playlist's snapshot ID against which you want to make the changes.
   * The API will validate that the specified items exist and in the specified positions and make the changes,
   * even if more recent changes have been made to the playlist.
   */
  snapshotId?: string;
}

export const playlistsTracksRequest2Schema: Schema<PlaylistsTracksRequest2> = object(
  {
    tracks: ['tracks', array(lazy(() => track1Schema))],
    snapshotId: ['snapshot_id', optional(string())],
  }
);
