/**
 * Spotify Web API with fixes and improvements from sonalluxLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, object, optional, Schema } from '../schema';
import {
  QueueObjectCurrentlyPlaying,
  queueObjectCurrentlyPlayingSchema,
} from './containers/queueObjectCurrentlyPlaying';
import {
  QueueObjectQueue,
  queueObjectQueueSchema,
} from './containers/queueObjectQueue';

export interface QueueObject {
  /** The currently playing track or episode. Can be `null`. */
  currentlyPlaying?: QueueObjectCurrentlyPlaying;
  /** The tracks or episodes in the queue. Can be empty. */
  queue?: QueueObjectQueue[];
}

export const queueObjectSchema: Schema<QueueObject> = object({
  currentlyPlaying: [
    'currently_playing',
    optional(queueObjectCurrentlyPlayingSchema),
  ],
  queue: ['queue', optional(array(queueObjectQueueSchema))],
});
