/**
 * Spotify Web API with fixes and improvements from sonalluxLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for ReasonEnum
 */
export enum ReasonEnum {
  Market = 'market',
  Product = 'product',
  Explicit = 'explicit',
}

/**
 * Schema for ReasonEnum
 */
export const reasonEnumSchema: Schema<ReasonEnum> = stringEnum(ReasonEnum);
