/**
 * Spotify Web API with fixes and improvements from sonalluxLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema, string } from '../schema';

export interface RecommendationSeedObject {
  /** The number of tracks available after min\_\* and max\_\* filters have been applied. */
  afterFilteringSize?: number;
  /** The number of tracks available after relinking for regional availability. */
  afterRelinkingSize?: number;
  /** A link to the full track or artist data for this seed. For tracks this will be a link to a Track Object. For artists a link to an Artist Object. For genre seeds, this value will be `null`. */
  href?: string;
  /** The id used to select this seed. This will be the same as the string used in the `seed_artists`, `seed_tracks` or `seed_genres` parameter. */
  id?: string;
  /** The number of recommended tracks available for this seed. */
  initialPoolSize?: number;
  /** The entity type of this seed. One of `artist`, `track` or `genre`. */
  type?: string;
}

export const recommendationSeedObjectSchema: Schema<RecommendationSeedObject> = object(
  {
    afterFilteringSize: ['afterFilteringSize', optional(number())],
    afterRelinkingSize: ['afterRelinkingSize', optional(number())],
    href: ['href', optional(string())],
    id: ['id', optional(string())],
    initialPoolSize: ['initialPoolSize', optional(number())],
    type: ['type', optional(string())],
  }
);
