/**
 * Spotify Web API with fixes and improvements from sonalluxLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, Schema } from '../schema';
import {
  RecommendationSeedObject,
  recommendationSeedObjectSchema,
} from './recommendationSeedObject';
import { TrackObject, trackObjectSchema } from './trackObject';

export interface RecommendationsObject {
  /** An array of recommendation seed objects. */
  seeds: RecommendationSeedObject[];
  /** An array of track objects ordered according to the parameters supplied. */
  tracks: TrackObject[];
}

export const recommendationsObjectSchema: Schema<RecommendationsObject> = object(
  {
    seeds: ['seeds', array(lazy(() => recommendationSeedObjectSchema))],
    tracks: ['tracks', array(lazy(() => trackObjectSchema))],
  }
);
