/**
 * Spotify Web API with fixes and improvements from sonalluxLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for ReleaseDatePrecisionEnum
 */
export enum ReleaseDatePrecisionEnum {
  Year = 'year',
  Month = 'month',
  Day = 'day',
}

/**
 * Schema for ReleaseDatePrecisionEnum
 */
export const releaseDatePrecisionEnumSchema: Schema<ReleaseDatePrecisionEnum> = stringEnum(
  ReleaseDatePrecisionEnum
);
