/**
 * Spotify Web API with fixes and improvements from sonalluxLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, number, object, optional, Schema } from '../schema';

export interface ResumePointObject {
  /** Whether or not the episode has been fully played by the user. */
  fullyPlayed?: boolean;
  /** The user's most recent position in the episode in milliseconds. */
  resumePositionMs?: number;
}

export const resumePointObjectSchema: Schema<ResumePointObject> = object({
  fullyPlayed: ['fully_played', optional(boolean())],
  resumePositionMs: ['resume_position_ms', optional(number())],
});
