/**
 * Spotify Web API with fixes and improvements from sonalluxLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema, string } from '../schema';
import { EpisodeObject, episodeObjectSchema } from './episodeObject';

export interface SavedEpisodeObject {
  /**
   * The date and time the episode was saved.
   * Timestamps are returned in ISO 8601 format as Coordinated Universal Time (UTC) with a zero offset: YYYY-MM-DDTHH:MM:SSZ.
   */
  addedAt?: string;
  /** Information about the episode. */
  episode?: EpisodeObject;
}

export const savedEpisodeObjectSchema: Schema<SavedEpisodeObject> = object({
  addedAt: ['added_at', optional(string())],
  episode: ['episode', optional(lazy(() => episodeObjectSchema))],
});
