/**
 * Spotify Web API with fixes and improvements from sonalluxLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import {
  PagingArtistObject,
  pagingArtistObjectSchema,
} from './pagingArtistObject';
import {
  PagingPlaylistObject,
  pagingPlaylistObjectSchema,
} from './pagingPlaylistObject';
import {
  PagingSimplifiedAlbumObject,
  pagingSimplifiedAlbumObjectSchema,
} from './pagingSimplifiedAlbumObject';
import {
  PagingSimplifiedAudiobookObject,
  pagingSimplifiedAudiobookObjectSchema,
} from './pagingSimplifiedAudiobookObject';
import {
  PagingSimplifiedEpisodeObject,
  pagingSimplifiedEpisodeObjectSchema,
} from './pagingSimplifiedEpisodeObject';
import {
  PagingSimplifiedShowObject,
  pagingSimplifiedShowObjectSchema,
} from './pagingSimplifiedShowObject';
import {
  PagingTrackObject,
  pagingTrackObjectSchema,
} from './pagingTrackObject';

export interface SearchItems {
  tracks?: PagingTrackObject;
  artists?: PagingArtistObject;
  albums?: PagingSimplifiedAlbumObject;
  playlists?: PagingPlaylistObject;
  shows?: PagingSimplifiedShowObject;
  episodes?: PagingSimplifiedEpisodeObject;
  audiobooks?: PagingSimplifiedAudiobookObject;
}

export const searchItemsSchema: Schema<SearchItems> = object({
  tracks: ['tracks', optional(lazy(() => pagingTrackObjectSchema))],
  artists: ['artists', optional(lazy(() => pagingArtistObjectSchema))],
  albums: ['albums', optional(lazy(() => pagingSimplifiedAlbumObjectSchema))],
  playlists: ['playlists', optional(lazy(() => pagingPlaylistObjectSchema))],
  shows: ['shows', optional(lazy(() => pagingSimplifiedShowObjectSchema))],
  episodes: [
    'episodes',
    optional(lazy(() => pagingSimplifiedEpisodeObjectSchema)),
  ],
  audiobooks: [
    'audiobooks',
    optional(lazy(() => pagingSimplifiedAudiobookObjectSchema)),
  ],
});
