/**
 * Spotify Web API with fixes and improvements from sonalluxLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema } from '../schema';
import { ModeEnum, modeEnumSchema } from './modeEnum';

export interface SectionObject {
  /** The starting point (in seconds) of the section. */
  start?: number;
  /** The duration (in seconds) of the section. */
  duration?: number;
  /** The confidence, from 0.0 to 1.0, of the reliability of the section's "designation". */
  confidence?: number;
  /** The overall loudness of the section in decibels (dB). Loudness values are useful for comparing relative loudness of sections within tracks. */
  loudness?: number;
  /** The overall estimated tempo of the section in beats per minute (BPM). In musical terminology, tempo is the speed or pace of a given piece and derives directly from the average beat duration. */
  tempo?: number;
  /** The confidence, from 0.0 to 1.0, of the reliability of the tempo. Some tracks contain tempo changes or sounds which don't contain tempo (like pure speech) which would correspond to a low value in this field. */
  tempoConfidence?: number;
  /** The estimated overall key of the section. The values in this field ranging from 0 to 11 mapping to pitches using standard Pitch Class notation (E.g. 0 = C, 1 = C♯/D♭, 2 = D, and so on). If no key was detected, the value is -1. */
  key?: number;
  /** The confidence, from 0.0 to 1.0, of the reliability of the key. Songs with many key changes may correspond to low values in this field. */
  keyConfidence?: number;
  /** Indicates the modality (major or minor) of a section, the type of scale from which its melodic content is derived. This field will contain a 0 for "minor", a 1 for "major", or a -1 for no result. Note that the major key (e.g. C major) could more likely be confused with the minor key at 3 semitones lower (e.g. A minor) as both keys carry the same pitches. */
  mode?: ModeEnum;
  /** The confidence, from 0.0 to 1.0, of the reliability of the `mode`. */
  modeConfidence?: number;
  /** An estimated time signature. The time signature (meter) is a notational convention to specify how many beats are in each bar (or measure). The time signature ranges from 3 to 7 indicating time signatures of "3/4", to "7/4". */
  timeSignature?: number;
  /** The confidence, from 0.0 to 1.0, of the reliability of the `time_signature`. Sections with time signature changes may correspond to low values in this field. */
  timeSignatureConfidence?: number;
}

export const sectionObjectSchema: Schema<SectionObject> = object({
  start: ['start', optional(number())],
  duration: ['duration', optional(number())],
  confidence: ['confidence', optional(number())],
  loudness: ['loudness', optional(number())],
  tempo: ['tempo', optional(number())],
  tempoConfidence: ['tempo_confidence', optional(number())],
  key: ['key', optional(number())],
  keyConfidence: ['key_confidence', optional(number())],
  mode: ['mode', optional(modeEnumSchema)],
  modeConfidence: ['mode_confidence', optional(number())],
  timeSignature: ['time_signature', optional(number())],
  timeSignatureConfidence: ['time_signature_confidence', optional(number())],
});
