/**
 * Spotify Web API with fixes and improvements from sonalluxLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  lazy,
  number,
  object,
  Schema,
  string,
} from '../schema';
import { CopyrightObject, copyrightObjectSchema } from './copyrightObject';
import {
  ExternalUrlObject,
  externalUrlObjectSchema,
} from './externalUrlObject';
import { ImageObject, imageObjectSchema } from './imageObject';

export interface ShowBase {
  /** A list of the countries in which the show can be played, identified by their [ISO 3166-1 alpha-2](http://en.wikipedia.org/wiki/ISO_3166-1_alpha-2) code. */
  availableMarkets: string[];
  /** The copyright statements of the show. */
  copyrights: CopyrightObject[];
  /** A description of the show. HTML tags are stripped away from this field, use `html_description` field in case HTML tags are needed. */
  description: string;
  /** A description of the show. This field may contain HTML tags. */
  htmlDescription: string;
  /** Whether or not the show has explicit content (true = yes it does; false = no it does not OR unknown). */
  explicit: boolean;
  /** External URLs for this show. */
  externalUrls: ExternalUrlObject;
  /** A link to the Web API endpoint providing full details of the show. */
  href: string;
  /** The [Spotify ID](/documentation/web-api/concepts/spotify-uris-ids) for the show. */
  id: string;
  /** The cover art for the show in various sizes, widest first. */
  images: ImageObject[];
  /** True if all of the shows episodes are hosted outside of Spotify's CDN. This field might be `null` in some cases. */
  isExternallyHosted: boolean;
  /** A list of the languages used in the show, identified by their [ISO 639](https://en.wikipedia.org/wiki/ISO_639) code. */
  languages: string[];
  /** The media type of the show. */
  mediaType: string;
  /** The name of the episode. */
  name: string;
  /** The publisher of the show. */
  publisher: string;
  /** The object type. */
  type: string;
  /** The [Spotify URI](/documentation/web-api/concepts/spotify-uris-ids) for the show. */
  uri: string;
  /** The total number of episodes in the show. */
  totalEpisodes: number;
}

export const showBaseSchema: Schema<ShowBase> = object({
  availableMarkets: ['available_markets', array(string())],
  copyrights: ['copyrights', array(lazy(() => copyrightObjectSchema))],
  description: ['description', string()],
  htmlDescription: ['html_description', string()],
  explicit: ['explicit', boolean()],
  externalUrls: ['external_urls', lazy(() => externalUrlObjectSchema)],
  href: ['href', string()],
  id: ['id', string()],
  images: ['images', array(lazy(() => imageObjectSchema))],
  isExternallyHosted: ['is_externally_hosted', boolean()],
  languages: ['languages', array(string())],
  mediaType: ['media_type', string()],
  name: ['name', string()],
  publisher: ['publisher', string()],
  type: ['type', string()],
  uri: ['uri', string()],
  totalEpisodes: ['total_episodes', number()],
});
