/**
 * Spotify Web API with fixes and improvements from sonalluxLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema, string } from '../schema';
import {
  ExternalUrlObject,
  externalUrlObjectSchema,
} from './externalUrlObject';
import { TypeEnum, typeEnumSchema } from './typeEnum';

export interface SimplifiedArtistObject {
  /** Known external URLs for this artist. */
  externalUrls?: ExternalUrlObject;
  /** A link to the Web API endpoint providing full details of the artist. */
  href?: string;
  /** The [Spotify ID](/documentation/web-api/concepts/spotify-uris-ids) for the artist. */
  id?: string;
  /** The name of the artist. */
  name?: string;
  /** The object type. */
  type?: TypeEnum;
  /** The [Spotify URI](/documentation/web-api/concepts/spotify-uris-ids) for the artist. */
  uri?: string;
}

export const simplifiedArtistObjectSchema: Schema<SimplifiedArtistObject> = object(
  {
    externalUrls: [
      'external_urls',
      optional(lazy(() => externalUrlObjectSchema)),
    ],
    href: ['href', optional(string())],
    id: ['id', optional(string())],
    name: ['name', optional(string())],
    type: ['type', optional(typeEnumSchema)],
    uri: ['uri', optional(string())],
  }
);
