/**
 * Spotify Web API with fixes and improvements from sonalluxLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema } from '../schema';

export interface TimeIntervalObject {
  /** The starting point (in seconds) of the time interval. */
  start?: number;
  /** The duration (in seconds) of the time interval. */
  duration?: number;
  /** The confidence, from 0.0 to 1.0, of the reliability of the interval. */
  confidence?: number;
}

export const timeIntervalObjectSchema: Schema<TimeIntervalObject> = object({
  start: ['start', optional(number())],
  duration: ['duration', optional(number())],
  confidence: ['confidence', optional(number())],
});
