/**
 * Spotify Web API with fixes and improvements from sonalluxLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for Type5Enum
 */
export enum Type5Enum {
  AudioFeatures = 'audio_features',
}

/**
 * Schema for Type5Enum
 */
export const type5EnumSchema: Schema<Type5Enum> = stringEnum(Type5Enum);
