/**
 * Spotify Web API with fixes and improvements from sonalluxLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  compositeAuthenticationProvider,
  OAuthConfiguration,
  requestAuthenticationProvider,
} from './authentication';
import { AuthorizationCodeAuthManager } from './authorizationCodeAuthManager';
import { Configuration } from './configuration';
import { OAuthToken } from './models/oAuthToken';

export function createAuthProviderFromConfig(
  config: Partial<Configuration>,
  oauth20: () => AuthorizationCodeAuthManager
) {
  const authConfig = {
    oauth20:
      config.authorizationCodeAuthCredentials &&
      requestAuthenticationProvider(
        config.authorizationCodeAuthCredentials.oAuthToken,
        oauth20TokenProvider(
          oauth20,
          config.authorizationCodeAuthCredentials.oAuthTokenProvider
        ),
        config.authorizationCodeAuthCredentials.oAuthOnTokenUpdate,
        {
          clockSkew: config.authorizationCodeAuthCredentials.oAuthClockSkew,
        } as OAuthConfiguration
      ),
  };

  return compositeAuthenticationProvider<
    keyof typeof authConfig,
    typeof authConfig
  >(authConfig);
}

function oauth20TokenProvider(
  oauth20: () => AuthorizationCodeAuthManager,
  defaultProvider:
    | ((
        lastOAuthToken: OAuthToken | undefined,
        authManager: AuthorizationCodeAuthManager
      ) => Promise<OAuthToken>)
    | undefined
): ((token: OAuthToken | undefined) => Promise<OAuthToken>) | undefined {
  return (token: OAuthToken | undefined) => {
    const manager = oauth20();
    if (defaultProvider === undefined) {
      return manager.updateToken(token);
    }
    return defaultProvider(token, manager);
  };
}
